# Welcome to Jekyll!
#
# If you change something here, please rerun `jekyll serve`

# Site settings
title: VeebS - Portfolio
description: sudo rm -rf /* and we're done. \n\n 
baseurl: "/portfolio"
url: "https://veebs1.github.io"

email: veebs04@gmail.com
disscord_username: veebs333
github_username:  VeebS1

paginate: 6

gems: [jekyll-paginate, kramdown]
markdown: kramdown
